(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Standard Model + Higgs-Portal DM",
  Authors -> {"Logan A. Morrison"},
  Version -> "1.0.0",
  Date -> "24. 01. 2020",
  Institutions -> {"University of California, Santa Cruz"},
  Emails -> {"loanmorr@ucsc.edu"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={{QCD, 0}, {QED, 0}};

FR$GoldstoneList={S[2], S[3]};

(*     Declared indices    *)

IndexRange[ Index[Gluon] ] = NoUnfold[ Range[ 8 ] ]

IndexRange[ Index[Generation] ] = Range[ 3 ]

IndexRange[ Index[Colour] ] = NoUnfold[ Range[ 3 ] ]

IndexRange[ Index[SU2W] ] = Range[ 3 ]

IndexRange[ Index[SU2D] ] = Range[ 2 ]

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "a",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> 0,
    Indices -> {} },

V[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Z",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

V[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "W",
    PropagatorType -> Sine,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

V[4] == {
    SelfConjugate -> True,
    Indices -> {Index[Gluon]},
    PropagatorLabel -> "G",
    PropagatorType -> Cycles,
    PropagatorArrow -> None,
    Mass -> 0 },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0,
    Indices -> {} },

U[2] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uZ",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MZ,
    Indices -> {} },

U[31] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, Q},
    PropagatorLabel -> "uWp",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[32] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber, -Q},
    PropagatorLabel -> "uWm",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MW,
    Indices -> {} },

U[4] == {
    SelfConjugate -> False,
    Indices -> {Index[Gluon]},
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "uG",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[1] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {LeptonNumber},
    PropagatorLabel -> "v",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> 0 },

F[2] == {
    Indices -> {Index[Generation]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q, LeptonNumber},
    PropagatorLabel -> "l",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Ml },

F[3] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {(2*Q)/3},
    PropagatorLabel -> "uq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Mu },

F[4] == {
    Indices -> {Index[Generation], Index[Colour]},
    SelfConjugate -> False,
    QuantumNumbers -> {-Q/3},
    PropagatorLabel -> "dq",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> Md },

F[5] == {
    SelfConjugate -> False,
    PropagatorLabel -> "~chi",
    PropagatorType -> Straight,
    PropagatorArrow -> Forward,
    Mass -> MDM,
    Indices -> {} },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "H",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MH,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "Go",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MZ,
    Indices -> {} },

S[3] == {
    SelfConjugate -> False,
    QuantumNumbers -> {Q},
    PropagatorLabel -> "GP",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MW,
    Indices -> {} },

S[4] == {
    SelfConjugate -> True,
    PropagatorLabel -> "S",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MSM,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ V[2] ] = GaugeXi[Z];
GaugeXi[ V[3] ] = GaugeXi[W];
GaugeXi[ V[4] ] = GaugeXi[G];
GaugeXi[ U[1] ] = GaugeXi[A];
GaugeXi[ U[2] ] = GaugeXi[Z];
GaugeXi[ U[31] ] = GaugeXi[W];
GaugeXi[ U[32] ] = GaugeXi[W];
GaugeXi[ U[4] ] = GaugeXi[G];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[Z];
GaugeXi[ S[3] ] = GaugeXi[W];

MZ[ ___ ] := MZ;
MW[ ___ ] := MW;
Ml[ 1 ] := Me;
Ml[ 2 ] := MMU;
Ml[ 3 ] := MTA;
Mu[ 1, _ ] := MU;
Mu[ 1 ] := MU;
Mu[ 2, _ ] := MC;
Mu[ 2 ] := MC;
Mu[ 3, _ ] := MT;
Mu[ 3 ] := MT;
Md[ 1, _ ] := MD;
Md[ 1 ] := MD;
Md[ 2, _ ] := MS;
Md[ 2 ] := MS;
Md[ 3, _ ] := MB;
Md[ 3 ] := MB;
MDM[ ___ ] := MDM;
MH[ ___ ] := MH;
MSM[ ___ ] := MSM;


TheLabel[ V[4, {__}] ] := TheLabel[V[4]];
TheLabel[ U[4, {__}] ] := TheLabel[U[4]];
TheLabel[ F[1, {1}] ] := "ve";
TheLabel[ F[1, {2}] ] := "vm";
TheLabel[ F[1, {3}] ] := "vt";
TheLabel[ F[2, {1}] ] := "e";
TheLabel[ F[2, {2}] ] := "mu";
TheLabel[ F[2, {3}] ] := "ta";
TheLabel[ F[3, {1, _}] ] := "u";
TheLabel[ F[3, {1}] ] := "u";
TheLabel[ F[3, {2, _}] ] := "c";
TheLabel[ F[3, {2}] ] := "c";
TheLabel[ F[3, {3, _}] ] := "t";
TheLabel[ F[3, {3}] ] := "t";
TheLabel[ F[4, {1, _}] ] := "d";
TheLabel[ F[4, {1}] ] := "d";
TheLabel[ F[4, {2, _}] ] := "s";
TheLabel[ F[4, {2}] ] := "s";
TheLabel[ F[4, {3, _}] ] := "b";
TheLabel[ F[4, {3}] ] := "b";


(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[2] , S[2] ] == {{((3*I)*(-(MSM^2*smix^2) + MH^2*(-1 + smix^2)))/vev^2, 0}},

C[ S[2] , S[2] , S[3] , -S[3] ] == {{(I*(-(MSM^2*smix^2) + MH^2*(-1 + smix^2)))/vev^2, 0}},

C[ S[3] , S[3] , -S[3] , -S[3] ] == {{((2*I)*(-(MSM^2*smix^2) + MH^2*(-1 + smix^2)))/vev^2, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{(I*(-1 + smix)*(1 + smix)*(MSM^2*smix^2 - MH^2*(-1 + smix^2)))/vev^2, 0}},

C[ S[3] , -S[3] , S[1] , S[1] ] == {{(I*(-1 + smix)*(1 + smix)*(MSM^2*smix^2 - MH^2*(-1 + smix^2)))/vev^2, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{((3*I)*(-1 + smix^2)^2*(-(MSM^2*smix^2) + MH^2*(-1 + smix^2)))/vev^2, 0}},

C[ S[2] , S[2] , S[4] , S[4] ] == {{(I*smix^2*(-(MSM^2*smix^2) + MH^2*(-1 + smix^2)))/vev^2, 0}},

C[ S[3] , -S[3] , S[4] , S[4] ] == {{(I*smix^2*(-(MSM^2*smix^2) + MH^2*(-1 + smix^2)))/vev^2, 0}},

C[ S[1] , S[1] , S[4] , S[4] ] == {{((3*I)*(-1 + smix)*smix^2*(1 + smix)*(MSM^2*smix^2 - MH^2*(-1 + smix^2)))/vev^2, 0}},

C[ S[4] , S[4] , S[4] , S[4] ] == {{((3*I)*smix^4*(-(MSM^2*smix^2) + MH^2*(-1 + smix^2)))/vev^2, 0}},

C[ S[2] , S[2] , S[1] , S[4] ] == {{(I*(-1 + smix)*smix*(1 + smix)*(-(MSM^2*smix^2) + MH^2*(-1 + smix^2)))/(Sqrt[1 - smix^2]*vev^2), 0}},

C[ S[3] , -S[3] , S[1] , S[4] ] == {{(I*(-1 + smix)*smix*(1 + smix)*(-(MSM^2*smix^2) + MH^2*(-1 + smix^2)))/(Sqrt[1 - smix^2]*vev^2), 0}},

C[ S[1] , S[4] , S[4] , S[4] ] == {{((3*I)*(-1 + smix)*smix^3*(1 + smix)*(-(MSM^2*smix^2) + MH^2*(-1 + smix^2)))/(Sqrt[1 - smix^2]*vev^2), 0}},

C[ S[1] , S[1] , S[1] , S[4] ] == {{((3*I)*(-1 + smix)*smix*(1 + smix)*Sqrt[1 - smix^2]*(-(MSM^2*smix^2) + MH^2*(-1 + smix^2)))/vev^2, 0}},

C[ S[1] , S[1] , S[4] ] == {{((-I)*(2*MH^2 + MSM^2)*(-1 + smix)*smix*(1 + smix))/vev, 0}},

C[ S[2] , S[2] , S[4] ] == {{(I*MSM^2*smix)/vev, 0}},

C[ S[3] , -S[3] , S[4] ] == {{(I*MSM^2*smix)/vev, 0}},

C[ S[4] , S[4] , S[4] ] == {{((3*I)*MSM^2*smix^3)/vev, 0}},

C[ S[2] , S[2] , S[1] ] == {{(I*MH^2*(-1 + smix)*(1 + smix))/(Sqrt[1 - smix^2]*vev), 0}},

C[ S[3] , -S[3] , S[1] ] == {{(I*MH^2*(-1 + smix)*(1 + smix))/(Sqrt[1 - smix^2]*vev), 0}},

C[ S[1] , S[4] , S[4] ] == {{(I*(MH^2 + 2*MSM^2)*(-1 + smix)*smix^2*(1 + smix))/(Sqrt[1 - smix^2]*vev), 0}},

C[ S[1] , S[1] , S[1] ] == {{((3*I)*MH^2*(-1 + smix)*(1 + smix)*Sqrt[1 - smix^2])/vev, 0}},

C[ S[3] , -U[31] , U[2] ] == {{((-I/4)*EL^2*(cw - sw)*(cw + sw)*vev)/(Sqrt[2]*cw*sw^2), 0}},

C[ S[3] , -U[2] , U[32] ] == {{((I/4)*EL^2*(cw^2 + sw^2)*vev)/(Sqrt[2]*cw*sw^2), 0}},

C[ -S[3] , -U[32] , U[2] ] == {{((-I/4)*EL^2*(cw - sw)*(cw + sw)*vev)/(Sqrt[2]*cw*sw^2), 0}},

C[ -S[3] , -U[2] , U[31] ] == {{((I/4)*EL^2*(cw^2 + sw^2)*vev)/(Sqrt[2]*cw*sw^2), 0}},

C[ S[1] , -U[2] , U[2] ] == {{((-I/8)*EL^2*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[2] , -U[32] , U[32] ] == {{-(EL^2*vev)/(8*sw^2), 0}},

C[ S[2] , -U[31] , U[31] ] == {{(EL^2*vev)/(8*sw^2), 0}},

C[ S[1] , -U[32] , U[32] ] == {{((-I/8)*EL^2*vev)/sw^2, 0}},

C[ S[1] , -U[31] , U[31] ] == {{((-I/8)*EL^2*vev)/sw^2, 0}},

C[ S[3] , -U[31] , U[1] ] == {{((-I/2)*EL^2*vev)/(Sqrt[2]*sw), 0}},

C[ -S[3] , -U[32] , U[1] ] == {{((-I/2)*EL^2*vev)/(Sqrt[2]*sw), 0}},

C[ S[3] , -S[3] , V[1] , V[1] ] == {{(2*I)*EL^2, 0}},

C[ S[3] , -S[3] , V[1] ] == {{(-I)*gc35, 0}, {I*gc35, 0}},

C[ -U[1] , U[32] , V[3] ] == {{I*gc36, 0}, {I*gc36, 0}, {0, 0}},

C[ -U[1] , U[31] , -V[3] ] == {{I*gc37, 0}, {I*gc37, 0}, {0, 0}},

C[ -U[32] , U[1] , -V[3] ] == {{I*gc38, 0}, {I*gc38, 0}, {0, 0}},

C[ -U[32] , U[32] , V[1] ] == {{I*gc39, 0}, {I*gc39, 0}, {0, 0}},

C[ -U[32] , U[32] , V[2] ] == {{I*gc40, 0}, {I*gc40, 0}, {0, 0}},

C[ -U[32] , U[2] , -V[3] ] == {{I*gc41, 0}, {I*gc41, 0}, {0, 0}},

C[ -U[31] , U[1] , V[3] ] == {{I*gc42, 0}, {I*gc42, 0}, {0, 0}},

C[ -U[31] , U[31] , V[1] ] == {{I*gc43, 0}, {I*gc43, 0}, {0, 0}},

C[ -U[31] , U[31] , V[2] ] == {{I*gc44, 0}, {I*gc44, 0}, {0, 0}},

C[ -U[31] , U[2] , V[3] ] == {{I*gc45, 0}, {I*gc45, 0}, {0, 0}},

C[ -U[2] , U[32] , V[3] ] == {{I*gc46, 0}, {I*gc46, 0}, {0, 0}},

C[ -U[2] , U[31] , -V[3] ] == {{I*gc47, 0}, {I*gc47, 0}, {0, 0}},

C[ -F[5] , F[5] , S[1] ] == {{I*gc48, 0}, {I*gc48, 0}},

C[ -F[5] , F[5] , S[4] ] == {{I*gc49, 0}, {I*gc49, 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] ] == {{-(gc50*SUNF[e1x2, e2x2, e3x2]), 0}, {gc50*SUNF[e1x2, e2x2, e3x2], 0}, {gc50*SUNF[e1x2, e2x2, e3x2], 0}, {-(gc50*SUNF[e1x2, e2x2, e3x2]), 0}, {-(gc50*SUNF[e1x2, e2x2, e3x2]), 0}, {gc50*SUNF[e1x2, e2x2, e3x2], 0}},

C[ V[4, {e1x2}] , V[4, {e2x2}] , V[4, {e3x2}] , V[4, {e4x2}] ] == {{(-I)*gc51*(SUNF[e1x2, e2x2, e3x2, e4x2] + SUNF[e1x2, e3x2, e2x2, e4x2]), 0}, {I*gc51*(SUNF[e1x2, e2x2, e3x2, e4x2] - SUNF[e1x2, e4x2, e2x2, e3x2]), 0}, {I*gc51*(SUNF[e1x2, e3x2, e2x2, e4x2] + SUNF[e1x2, e4x2, e2x2, e3x2]), 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -S[3] ] == {{gc52L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc52R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[2] ] == {{gc53L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc53R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[4] ] == {{I*gc54L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc54R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[1] ] == {{I*gc55L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc55R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -S[3] ] == {{gc56[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[2] ] == {{gc57L[e1x2, e2x2], 0}, {gc57R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[4] ] == {{I*gc58L[e1x2, e2x2], 0}, {I*gc58R[e1x2, e2x2], 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , S[1] ] == {{I*gc59L[e1x2, e2x2], 0}, {I*gc59R[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , S[3] ] == {{gc60L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc60R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[2] ] == {{gc61L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {gc61R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[4] ] == {{I*gc62L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc62R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , S[1] ] == {{I*gc63L[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc63R[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ S[2] , -S[3] , V[1] , V[3] ] == {{((-I/2)*EL^2)/sw, 0}},

C[ -S[3] , S[4] , V[1] , V[3] ] == {{(EL^2*smix)/(2*sw), 0}},

C[ -S[3] , S[1] , V[1] , V[3] ] == {{-(EL^2*Sqrt[1 - smix^2])/(2*sw), 0}},

C[ -S[3] , V[1] , V[3] ] == {{-(EL^2*vev)/(2*sw), 0}},

C[ S[2] , -S[3] , V[3] ] == {{(-I)*gc68, 0}, {I*gc68, 0}},

C[ -S[3] , S[4] , V[3] ] == {{-gc69, 0}, {gc69, 0}},

C[ -S[3] , S[1] , V[3] ] == {{-gc70, 0}, {gc70, 0}},

C[ V[1] , V[3] , -V[3] ] == {{(-I)*gc71, 0}, {I*gc71, 0}, {I*gc71, 0}, {(-I)*gc71, 0}, {(-I)*gc71, 0}, {I*gc71, 0}},

C[ S[2] , S[3] , V[1] , -V[3] ] == {{((-I/2)*EL^2)/sw, 0}},

C[ S[3] , S[4] , V[1] , -V[3] ] == {{-(EL^2*smix)/(2*sw), 0}},

C[ S[3] , S[1] , V[1] , -V[3] ] == {{(EL^2*Sqrt[1 - smix^2])/(2*sw), 0}},

C[ S[3] , V[1] , -V[3] ] == {{(EL^2*vev)/(2*sw), 0}},

C[ S[2] , S[3] , -V[3] ] == {{(-I)*gc76, 0}, {I*gc76, 0}},

C[ S[3] , S[4] , -V[3] ] == {{-gc77, 0}, {gc77, 0}},

C[ S[3] , S[1] , -V[3] ] == {{-gc78, 0}, {gc78, 0}},

C[ S[2] , S[2] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[3] , -S[3] , V[3] , -V[3] ] == {{((I/2)*EL^2)/sw^2, 0}},

C[ S[1] , S[1] , V[3] , -V[3] ] == {{((-I/2)*EL^2*(-1 + smix)*(1 + smix))/sw^2, 0}},

C[ S[4] , S[4] , V[3] , -V[3] ] == {{((I/2)*EL^2*smix^2)/sw^2, 0}},

C[ S[1] , S[4] , V[3] , -V[3] ] == {{((-I/2)*EL^2*smix*Sqrt[1 - smix^2])/sw^2, 0}},

C[ S[4] , V[3] , -V[3] ] == {{((-I/2)*EL^2*smix*vev)/sw^2, 0}},

C[ S[1] , V[3] , -V[3] ] == {{((I/2)*EL^2*Sqrt[1 - smix^2]*vev)/sw^2, 0}},

C[ V[1] , V[1] , V[3] , -V[3] ] == {{(-I)*gc86, 0}, {(-I)*gc86, 0}, {(2*I)*gc86, 0}},

C[ V[3] , -V[3] , V[2] ] == {{(-I)*gc87, 0}, {I*gc87, 0}, {I*gc87, 0}, {(-I)*gc87, 0}, {(-I)*gc87, 0}, {I*gc87, 0}},

C[ V[3] , V[3] , -V[3] , -V[3] ] == {{(-I)*gc88, 0}, {(-I)*gc88, 0}, {(2*I)*gc88, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , S[3] ] == {{0, 0}, {gc89R[e1x2, e2x2], 0}},

C[ S[3] , -S[3] , V[1] , V[2] ] == {{(I*EL^2*(cw - sw)*(cw + sw))/(cw*sw), 0}},

C[ S[2] , S[4] , V[2] ] == {{-gc91, 0}, {gc91, 0}},

C[ S[2] , S[1] , V[2] ] == {{-gc92, 0}, {gc92, 0}},

C[ S[3] , -S[3] , V[2] ] == {{(-I)*gc93, 0}, {I*gc93, 0}},

C[ S[2] , -S[3] , V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ -S[3] , S[4] , V[3] , V[2] ] == {{-(EL^2*smix)/(2*cw), 0}},

C[ -S[3] , S[1] , V[3] , V[2] ] == {{(EL^2*Sqrt[1 - smix^2])/(2*cw), 0}},

C[ -S[3] , V[3] , V[2] ] == {{(EL^2*vev)/(2*cw), 0}},

C[ S[2] , S[3] , -V[3] , V[2] ] == {{((I/2)*EL^2)/cw, 0}},

C[ S[3] , S[4] , -V[3] , V[2] ] == {{(EL^2*smix)/(2*cw), 0}},

C[ S[3] , S[1] , -V[3] , V[2] ] == {{-(EL^2*Sqrt[1 - smix^2])/(2*cw), 0}},

C[ S[3] , -V[3] , V[2] ] == {{-(EL^2*vev)/(2*cw), 0}},

C[ V[1] , V[3] , -V[3] , V[2] ] == {{(-2*I)*gc102, 0}, {I*gc102, 0}, {I*gc102, 0}},

C[ S[2] , S[2] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[3] , -S[3] , V[2] , V[2] ] == {{((I/2)*EL^2*(cw - sw)^2*(cw + sw)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[1] , V[2] , V[2] ] == {{((-I/2)*EL^2*(-1 + smix)*(1 + smix)*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[4] , S[4] , V[2] , V[2] ] == {{((I/2)*EL^2*smix^2*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[1] , S[4] , V[2] , V[2] ] == {{((-I/2)*EL^2*smix*Sqrt[1 - smix^2]*(cw^2 + sw^2)^2)/(cw^2*sw^2), 0}},

C[ S[4] , V[2] , V[2] ] == {{((-I/2)*EL^2*smix*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ S[1] , V[2] , V[2] ] == {{((I/2)*EL^2*Sqrt[1 - smix^2]*(cw^2 + sw^2)^2*vev)/(cw^2*sw^2), 0}},

C[ V[3] , -V[3] , V[2] , V[2] ] == {{(-I)*gc110, 0}, {(-I)*gc110, 0}, {(2*I)*gc110, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[1] ] == {{I*gc111*IndexDelta[e1x2, e2x2], 0}, {I*gc111*IndexDelta[e1x2, e2x2], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[1] ] == {{I*gc112*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc112*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[1] ] == {{I*gc113*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc113*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc114*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc114*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[4, {e3x2}] ] == {{I*gc115*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}, {I*gc115*IndexDelta[e1x2, e2x2]*SUNT[e3x2, e1x3, e2x3], 0}},

C[ -F[3, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[3] ] == {{I*gc116[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[4, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , -V[3] ] == {{I*gc117[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {0, 0}},

C[ -F[1, {e1x2}] , F[2, {e2x2}] , V[3] ] == {{I*gc118*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[1, {e2x2}] , -V[3] ] == {{I*gc119*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[3, {e1x2, e1x3}] , F[3, {e2x2, e2x3}] , V[2] ] == {{I*gc120L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc120R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[4, {e1x2, e1x3}] , F[4, {e2x2, e2x3}] , V[2] ] == {{I*gc121L*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}, {I*gc121R*IndexDelta[e1x2, e2x2]*IndexDelta[e1x3, e2x3], 0}},

C[ -F[1, {e1x2}] , F[1, {e2x2}] , V[2] ] == {{I*gc122*IndexDelta[e1x2, e2x2], 0}, {0, 0}},

C[ -F[2, {e1x2}] , F[2, {e2x2}] , V[2] ] == {{I*gc123L*IndexDelta[e1x2, e2x2], 0}, {I*gc123R*IndexDelta[e1x2, e2x2], 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc35 -> -EL,
     gc36 -> EL,
     gc37 -> -EL,
     gc38 -> EL,
     gc39 -> -EL,
     gc40 -> -((cw*EL)/sw),
     gc41 -> (cw*EL)/sw,
     gc42 -> -EL,
     gc43 -> EL,
     gc44 -> (cw*EL)/sw,
     gc45 -> -((cw*EL)/sw),
     gc46 -> (cw*EL)/sw,
     gc47 -> -((cw*EL)/sw),
     gc48 -> -(gSXX*smix),
     gc49 -> -(gSXX*Sqrt[1 - smix^2]),
     gc50 -> -GS,
     gc51 -> -GS^2,
     gc52L[e1x2_, e2x2_] -> IndexSum[Conjugate[CKM[e2x2, Generation$1]]*Conjugate[yd[Generation$1, e1x2]], {Generation$1, 1, 3}],
     gc52R[e1x2_, e2x2_] -> -IndexSum[Conjugate[CKM[Generation$1, e1x2]]*yu[Generation$1, e2x2], {Generation$1, 1, 3}],
     gc53L[e1x2_, e2x2_] -> -(Conjugate[yd[e2x2, e1x2]]/Sqrt[2]),
     gc53R[e1x2_, e2x2_] -> yd[e1x2, e2x2]/Sqrt[2],
     gc54L[e1x2_, e2x2_] -> (smix*Conjugate[yd[e2x2, e1x2]])/Sqrt[2],
     gc54R[e1x2_, e2x2_] -> (smix*yd[e1x2, e2x2])/Sqrt[2],
     gc55L[e1x2_, e2x2_] -> -((Sqrt[1 - smix^2]*Conjugate[yd[e2x2, e1x2]])/Sqrt[2]),
     gc55R[e1x2_, e2x2_] -> -((Sqrt[1 - smix^2]*yd[e1x2, e2x2])/Sqrt[2]),
     gc56[e1x2_, e2x2_] -> Conjugate[yl[e2x2, e1x2]],
     gc57L[e1x2_, e2x2_] -> -(Conjugate[yl[e2x2, e1x2]]/Sqrt[2]),
     gc57R[e1x2_, e2x2_] -> yl[e1x2, e2x2]/Sqrt[2],
     gc58L[e1x2_, e2x2_] -> (smix*Conjugate[yl[e2x2, e1x2]])/Sqrt[2],
     gc58R[e1x2_, e2x2_] -> (smix*yl[e1x2, e2x2])/Sqrt[2],
     gc59L[e1x2_, e2x2_] -> -((Sqrt[1 - smix^2]*Conjugate[yl[e2x2, e1x2]])/Sqrt[2]),
     gc59R[e1x2_, e2x2_] -> -((Sqrt[1 - smix^2]*yl[e1x2, e2x2])/Sqrt[2]),
     gc60L[e1x2_, e2x2_] -> IndexSum[CKM[Generation$1, e2x2]*Conjugate[yu[Generation$1, e1x2]], {Generation$1, 1, 3}],
     gc60R[e1x2_, e2x2_] -> -IndexSum[CKM[e1x2, Generation$1]*yd[Generation$1, e2x2], {Generation$1, 1, 3}],
     gc61L[e1x2_, e2x2_] -> Conjugate[yu[e2x2, e1x2]]/Sqrt[2],
     gc61R[e1x2_, e2x2_] -> -(yu[e1x2, e2x2]/Sqrt[2]),
     gc62L[e1x2_, e2x2_] -> (smix*Conjugate[yu[e2x2, e1x2]])/Sqrt[2],
     gc62R[e1x2_, e2x2_] -> (smix*yu[e1x2, e2x2])/Sqrt[2],
     gc63L[e1x2_, e2x2_] -> -((Sqrt[1 - smix^2]*Conjugate[yu[e2x2, e1x2]])/Sqrt[2]),
     gc63R[e1x2_, e2x2_] -> -((Sqrt[1 - smix^2]*yu[e1x2, e2x2])/Sqrt[2]),
     gc68 -> EL/(2*sw),
     gc69 -> (EL*smix)/(2*sw),
     gc70 -> -(EL*Sqrt[1 - smix^2])/(2*sw),
     gc71 -> EL,
     gc76 -> -EL/(2*sw),
     gc77 -> (EL*smix)/(2*sw),
     gc78 -> -(EL*Sqrt[1 - smix^2])/(2*sw),
     gc86 -> -EL^2,
     gc87 -> (cw*EL)/sw,
     gc88 -> EL^2/sw^2,
     gc89R[e1x2_, e2x2_] -> -yl[e1x2, e2x2],
     gc91 -> (EL*smix*(cw^2 + sw^2))/(2*cw*sw),
     gc92 -> -(EL*Sqrt[1 - smix^2]*(cw^2 + sw^2))/(2*cw*sw),
     gc93 -> -(cw*EL)/(2*sw) + (EL*sw)/(2*cw),
     gc102 -> (cw*EL^2)/sw,
     gc110 -> -((cw^2*EL^2)/sw^2),
     gc111 -> -EL,
     gc112 -> (2*EL)/3,
     gc113 -> -EL/3,
     gc114 -> GS,
     gc115 -> GS,
     gc116[e1x2_, e2x2_] -> (EL*CKM[e1x2, e2x2])/(Sqrt[2]*sw),
     gc117[e1x2_, e2x2_] -> (EL*Conjugate[CKM[e2x2, e1x2]])/(Sqrt[2]*sw),
     gc118 -> EL/(Sqrt[2]*sw),
     gc119 -> EL/(Sqrt[2]*sw),
     gc120L -> (cw*EL)/(2*sw) - (EL*sw)/(6*cw),
     gc120R -> (-2*EL*sw)/(3*cw),
     gc121L -> -(EL*(3*cw^2 + sw^2))/(6*cw*sw),
     gc121R -> (EL*sw)/(3*cw),
     gc122 -> (EL*(cw^2 + sw^2))/(2*cw*sw),
     gc123L -> -(EL*(cw^2 - sw^2))/(2*cw*sw),
     gc123R -> (EL*sw)/cw};

