(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)
(*                                                                             *)
(*         This file has been automatically generated by FeynRules.            *)
(*                                                                             *)
(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)


FR$ModelInformation={
  ModelName->"Abelian Higgs",
  Authors -> {"Logan A. Morrison"},
  Version -> "1.0",
  Date -> "25. 01. 2020",
  Institutions -> {"University of California, Santa Cruz"},
  Emails -> {"loanmorr@ucsc.edu"}};

FR$ClassesTranslation={};

FR$InteractionOrderPerturbativeExpansion={};

FR$GoldstoneList={S[2]};

(*     Declared indices    *)

(*     Declared particles    *)

M$ClassesDescription = {
V[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "A",
    PropagatorType -> Sine,
    PropagatorArrow -> None,
    Mass -> MA,
    Indices -> {} },

S[1] == {
    SelfConjugate -> True,
    PropagatorLabel -> "h",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> mh,
    Indices -> {} },

S[2] == {
    SelfConjugate -> True,
    PropagatorLabel -> "G0",
    PropagatorType -> ScalarDash,
    PropagatorArrow -> None,
    Mass -> MA,
    Indices -> {} },

U[1] == {
    SelfConjugate -> False,
    QuantumNumbers -> {GhostNumber},
    PropagatorLabel -> "ghA",
    PropagatorType -> GhostDash,
    PropagatorArrow -> Forward,
    Mass -> MA,
    Indices -> {} }
}


(*        Definitions       *)

GaugeXi[ V[1] ] = GaugeXi[A];
GaugeXi[ S[1] ] = 1;
GaugeXi[ S[2] ] = GaugeXi[A];
GaugeXi[ U[1] ] = GaugeXi[A];

MA[ ___ ] := MA;
mh[ ___ ] := mh;




(*      Couplings (calculated by FeynRules)      *)

M$CouplingMatrices = {

C[ S[2] , S[2] , S[1] ] == {{((-I)*mh^2*qe)/MA, 0}},

C[ S[1] , S[1] , S[1] ] == {{((-3*I)*mh^2*qe)/MA, 0}},

C[ S[2] , S[2] , S[2] , S[2] ] == {{((-3*I)*mh^2*qe^2)/MA^2, 0}},

C[ S[2] , S[2] , S[1] , S[1] ] == {{((-I)*mh^2*qe^2)/MA^2, 0}},

C[ S[1] , S[1] , S[1] , S[1] ] == {{((-3*I)*mh^2*qe^2)/MA^2, 0}},

C[ S[1] , V[1] , V[1] ] == {{(2*I)*MA*qe, 0}},

C[ S[2] , S[2] , V[1] , V[1] ] == {{(2*I)*qe^2, 0}},

C[ S[1] , S[1] , V[1] , V[1] ] == {{(2*I)*qe^2, 0}},

C[ S[2] , S[1] , V[1] ] == {{-gc9, 0}, {gc9, 0}}

}

(* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *)

(* Parameter replacement lists (These lists were created by FeynRules) *)

(* FA Couplings *)

M$FACouplings = {
     gc9 -> qe};

